### ISSUE TITLE
Cannot connect to X server at travis.

### ISSUE THREAD

**Issue by tushar-rishav** [tushar-rishav/code2pdf#12]
Seems  like `XAUTHORITY` and `DISPLAY` env vars aren't set at Travis. Hence, the failure to connect

**Comment by AbdealiLoKo** [comment]
What does failure to connect mean ?

**Comment by tushar-rishav** [comment]
Build fails [Here](https://travis-ci.org/tushar-rishav/code2pdf/builds)
Plausible causes are:
- `XAUTHORITY` and `DISPLAY` isn't set. 
- Running as a root
- Issue with dbus setup. So message passing from one session to another is failing.
