### ISSUE TITLE
Compatibility with pyqt5?

### ISSUE THREAD

**Issue by shohpfizer** [tushar-rishav/code2pdf#19]
Hi, I would like to know if there is any possibility to run this program with pyqt5? The latest version of Anaconda is not allowing me to downgrade pyqt without messing the installation up.

Thanks!

**Comment by tushar-rishav** [comment]
@shohpfizer Hi, I haven't tested on PyQt5 yet. Did you notice any incompatibilities? Btw, I'd suggest you use virtualenv to isolate the dependencies.

**Comment by tushar-rishav** [comment]
Taken care in https://github.com/tushar-rishav/code2pdf/pull/29 . Should be okay now.
