### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by sananth12** [tushar-rishav/code2pdf#4]
The current tests doesn't actually tell you anything useful.
Please add unit tests. If you fell you can't write unit tests, then you might wanna reconsider the design itself.

**Comment by sananth12** [comment]
@tushar-rishav the new test branch looks good. You'll still need some re-factoring to make your code testable but it's a good place to start for now.

**Comment by tushar-rishav** [comment]
@sananth12 I am trying to figure out how to handle PyQt dependencies. Currently, any dependencies are being fetched from PyPi during installation. But it seems PyQt can't be fetched from PyPi directly. Consequently, missing PyQt packages throws an error while running tests with Travis. What I am looking for is a way to fire the PyQt installation before installing code2pdf. Any suggestions?
