### ISSUE TITLE
Grow Up

### ISSUE THREAD

**Issue by torifat** [tushar-rishav/code2pdf#9]
![image](https://cloud.githubusercontent.com/assets/208544/14121049/99b3cd86-f617-11e5-8ebd-b04dab334add.png)

**Comment by tushar-rishav** [comment]
@torifat  I understand. That was [purely experimental](https://github.com/jeroenvisser101/notice-me/commit/fe263d52dfac74f66315d01c1abf4b1f9e3da3e3#commitcomment-16883702). I wish I could undo the changes.

**Comment by tushar-rishav** [comment]
Closing in favor of explanation at [Readme](https://github.com/tushar-rishav/code2pdf/blob/master/README.md)

**Comment by MikeChongCan** [comment]
👎🏻
